project:
  type: website
  output-dir: docs     # <- GitHub Pages will serve from /docs

website:
  title: "Target Trial Emulation and Causal Inference Tutorials"
  site-url: https://uqualitycausal.github.io/TTECausalR/
  site-path: /TTECausalR/
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Tutorials"
        menu:
          - href: TTEdemoSig.html
            text: "Preparing Analysis Data by Emulating A Single Target Trial"
          - href: TTEdemoSeq.html
            text: "Preparing Analysis Data by Emulating A Sequence of Target Trials"
          - href: IntentionToTreat.html
            text: "Introduction to Causal Inference and Intention to Treat Analysis"
          - href: PerProtocol.html
            text: "Per-protocol Analysis"
          - href: DRpseudo.html
            text: "Doubly Robust Estimation of Average Treatment Effects Using Pseudo Observations"
          - href: DRaipwcc.html
            text: "Augmented Inverse Probability Weighted Complete Case Estimator for Survival Outcomes"
  repo-url: https://github.com/UQualityCausal/TTECausalR
  repo-actions: [source, issue]   # "View source" / "Open issue" buttons

format:
  html:
    theme: cosmo
    toc: true
    code-copy: true
    code-fold: show
    df-print: paged

execute:
  freeze: auto         # re-render only when source changes
  cache: true          # cache chunk results
